{{- if (empty .Values.publicDomain) }}
{{- fail "Please provide a value for `.Values.publicDomain`." }}
{{- end }}

{{- if (and .Values.ui.enabled (empty .Values.ui.publicDomain)) }}
{{- fail "Please provide a value for `.Values.ui.publicDomain`." }}
{{- end }}

{{- if (and .Values.useExistingSecret (empty .Values.defaultUserCredentialsSecret)) }}
{{- fail "Please provide a secret name for `.Values.defaultUserCredentialSecret`" }}
{{- end }}
