---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3gw-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4}}
data:
{{- if .Values.ui.enabled }}
{{- if or .Values.useCertManager .Values.tls.publicDomain.crt }}
  RGW_SERVICE_URL: 'https://{{ .Values.serviceName }}.{{ .Values.publicDomain }}'
{{- else}}
  RGW_SERVICE_URL: 'http://{{ .Values.serviceName }}.{{ .Values.publicDomain }}'
{{- end }}
{{- end }}
