apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-reverseproxy-config
  namespace: {{ include "custom.namespace" . }}
data:
{{ tpl (.Files.Glob "conf/config.yaml").AsConfig . | indent 2 }}
