{{- if ne .Values.deployAsSidecar true }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-reverseproxy
  namespace: {{ include "custom.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-reverseproxy
  namespace: {{ include "custom.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-reverseproxy
    namespace: {{ include "custom.namespace" . }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-reverseproxy
  apiGroup: rbac.authorization.k8s.io
{{- end }}